skip init and login if already done

diff --git a/modules/vault/scripts/initialize-vault b/modules/vault/scripts/initialize-vault
--- a/modules/vault/scripts/initialize-vault
+++ b/modules/vault/scripts/initialize-vault
@@ -85,7 +85,7 @@ echo "Removing any previous host keys for: $hostname,$privateip"
 ssh-keygen -R $hostname
 ssh-keygen -R $privateip
 printf "\nAdding hostkeys using AWS CLI query for $hostname,$privateip\n" # A seperate channel should always be used to add hsot keys, so we use the cli.
-echo "The first time an instance is starting this may take 2-3 minutes."
+printf "The first time an instance is starting this may take 2-3 minutes.\n\n"
 # known_hosts_fragment=$(aws ec2 get-console-output --instance-id i-0c0f3ff0b0c79c4e2 | jq .Output -r |sed -n -e '1,/-----BEGIN SSH HOST KEY KEYS-----/d; /-----END SSH HOST KEY KEYS-----/q; p' | grep ecdsa-sha2-nistp256 | awk -v host=i-0c0f3ff0b0c79c4e2.node.consul,10.1.0.15 -v space=' ' '{ print host space $1 space $2 }')
 
 get_host_key() {
@@ -113,18 +113,29 @@ else
     echo "Added to known hosts: $known_hosts_fragment"
 fi
 
-result=$(ssh -l ubuntu $hostname "bash -s" < "$SCRIPTDIR/initialize-ssh")
+# if vault is already initialised, then login.
+initialised=true
+vault status | grep -m 1 "Initialized.*true" || initialised=false
+if [[ "$initialised" == "true" ]]; then
+  echo "Vault is already Initialized."
+  exit
+else
+  result=$(ssh -l ubuntu $hostname "bash -s" < "$SCRIPTDIR/initialize-ssh")
 
-recovery_key=$(echo "$result" | awk '/^Recovery Key 1:/ { print $4 ; exit }')
-initial_root_token=$(echo "$result" | awk '/^Initial Root Token:/ { print $4 ; exit }')
+  recovery_key=$(echo "$result" | awk '/^Recovery Key 1:/ { print $4 ; exit }')
+  initial_root_token=$(echo "$result" | awk '/^Initial Root Token:/ { print $4 ; exit }')
 
-echo "recovery_key: $recovery_key"
-echo "initial_root_token: $initial_root_token"
-if [[ -z "$initial_root_token" ]] || [[ -z "$recovery_key" ]]; then
   echo ""
-  echo "Warning: Did not initialize vault:"
-  echo "$result"
-  exit 1
+  echo "recovery_key: $recovery_key"
+  echo "initial_root_token: $initial_root_token"
+  echo ""
+
+  if [[ -z "$initial_root_token" ]] || [[ -z "$recovery_key" ]]; then
+    echo ""
+    echo "Warning: Did not initialize vault:"
+    echo "$result"
+    exit
+  fi
 fi
 
 get_vault_ip() {
@@ -136,4 +147,12 @@ retryifnooutput \
     "Querying vault IP's exist for service..." \
     "Failed to hosts for vault.service.consul."
 
-vault login --no-print $initial_root_token
+output=$(vault token lookup) && exit_status=0 || exit_status=$?
+errors=$(echo "$output") | grep '^{' | jq -r .errors
+echo "$output"
+if [[ $exit_status -eq 0 && -z "$errors" ]]; then
+    echo "...Already logged in"
+else
+    echo "...Logging in. Or exit and use: vault login --no-print"
+    vault login --no-print $initial_root_token
+fi
