test again

diff --git a/modules/terraform-aws-bastion/modules/bastion/cloud-init.yaml b/modules/terraform-aws-bastion/modules/bastion/cloud-init.yaml
--- a/modules/terraform-aws-bastion/modules/bastion/cloud-init.yaml
+++ b/modules/terraform-aws-bastion/modules/bastion/cloud-init.yaml
@@ -47,38 +47,40 @@ bootcmd:
     done
     systemctl restart network
 
-    echo $SHELL
+    echo "TEST TEST TEST"
 
-    set -e
+    echo "$SHELL"
 
-    # Send the log output from this script to user-data.log, syslog, and the console
-    # From: https://alestic.com/2010/12/ec2-user-data-output/
-    exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
+    # set -e
 
-    # Log the given message. All logs are written to stderr with a timestamp.
-    function log {
-      local -r message="$1"
-      local -r timestamp=$(date +"%Y-%m-%d %H:%M:%S")
-      >&2 echo -e "$timestamp $message"
-    }
+    # # Send the log output from this script to user-data.log, syslog, and the console
+    # # From: https://alestic.com/2010/12/ec2-user-data-output/
+    # exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
 
-    function has_yum {
-      [[ -n "$(command -v yum)" ]]
-    }
+    # # Log the given message. All logs are written to stderr with a timestamp.
+    # function log {
+    #   local -r message="$1"
+    #   local -r timestamp=$(date +"%Y-%m-%d %H:%M:%S")
+    #   >&2 echo -e "$timestamp $message"
+    # }
 
-    if $(has_yum); then
-      hostname=$(hostname -s) # in centos, failed dns lookup can cause commands to slowdown
-      echo "127.0.0.1   $hostname.${aws_domain} $hostname" | tee -a /etc/hosts
-    fi
+    # function has_yum {
+    #   [[ -n "$(command -v yum)" ]]
+    # }
 
-    log "hostname: $(hostname)"
-    log "hostname: $(hostname -f) $(hostname -s)"
+    # if $(has_yum); then
+    #   hostname=$(hostname -s) # in centos, failed dns lookup can cause commands to slowdown
+    #   echo "127.0.0.1   $hostname.${aws_domain} $hostname" | tee -a /etc/hosts
+    # fi
 
-    log "test sudo delay"
-    log "no sudo"
-    sudo echo "sudo"
-    log "sudo"
-    log "no sudo"
-    sudo echo "sudo"
-    log "sudo"
-    log "no sudo"
+    # log "hostname: $(hostname)"
+    # log "hostname: $(hostname -f) $(hostname -s)"
+
+    # log "test sudo delay"
+    # log "no sudo"
+    # sudo echo "sudo"
+    # log "sudo"
+    # log "no sudo"
+    # sudo echo "sudo"
+    # log "sudo"
+    # log "no sudo"
