update init backend procedure

diff --git a/init_host b/init_host
--- a/init_host
+++ b/init_host
@@ -19,26 +19,6 @@ SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # 
 
 source $SCRIPTDIR/update_vars.sh
 
-# Raise error if var isn't defined.
-if [[ -z "$AWS_DEFAULT_REGION" ]]; then
-    exit_if_error 1 "AWS_DEFAULT_REGION not defined."
-fi
-if [[ -z "$TF_VAR_bucket_extension" ]]; then
-    exit_if_error 1 "TF_VAR_bucket_extension not defined."
-fi
-
-local -r private_key_path="/home/$HOME/.ssh/id_rsa"
-if test ! -f "$private_key_path"; then
-    echo "Generating private / public key pair"
-    ssh-keygen -q -t rsa -f  -C "" -N ""
-fi
-
-source $SCRIPTDIR/update_vars.sh
-
-cd $SCRIPTDIR/modules/terraform-s3-bucket-remote-backend
-./generate-plan
-terraform apply -input=false tfplan
-
 cd $SCRIPTDIR/modules/terraform-s3-bucket-software
 ./generate-plan
 terraform apply -input=false tfplan # Ensure S3 Bucket exists to persist software
@@ -50,6 +30,26 @@ terraform apply -input=false tfplan # Ensure S3 ucket exists to persist vault ba
 cd $SCRIPTDIR/modules/terraform-aws-iam-profile-packer
 ./generate-plan
 terraform apply -input=false tfplan # Ensure profile exists enabling S3 Access.
+
+# Raise error if var isn't defined.
+if [[ -z "$AWS_DEFAULT_REGION" ]]; then
+    exit_if_error 1 "AWS_DEFAULT_REGION not defined."
+fi
+if [[ -z "$TF_VAR_bucket_extension" ]]; then
+    exit_if_error 1 "TF_VAR_bucket_extension not defined."
+fi
+
+local -r private_key_path="/home/$HOME/.ssh/id_rsa"
+if test ! -f "$private_key_path"; then
+    echo "Generating private / public key pair, since it did not exist yet..."
+    ssh-keygen -q -t rsa -f "$private_key_path" -C '' -N ''
+fi
+if test ! -f "$private_key_path"; then
+    echo "Error generating key pair at: $private_key_path"
+    exit 1
+fi
+
+source $SCRIPTDIR/update_vars.sh
 
 cd $SCRIPTDIR/modules/terraform-aws-instance-key-pair
 ./generate-plan
