request vpn files to client

diff --git a/wake b/wake
--- a/wake
+++ b/wake
@@ -1,6 +1,17 @@
 #!/bin/bash
 set -e
 
+exit_if_error() {
+  local exit_code=$1
+  shift
+  [[ $exit_code ]] &&               # do nothing if no error code passed
+    ((exit_code != 0)) && {         # do nothing if error code is 0
+      printf 'ERROR: %s\n' "$@" >&2 # we can use better logging here
+      exit "$exit_code"             # we could also check to make sure
+                                    # error code is numeric when passed
+    }
+}
+
 SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script
 
 source $SCRIPTDIR/update_vars.sh
@@ -12,14 +23,6 @@ fi
 if [[ -z "$TF_VAR_bucket_extension" ]]; then
     exit_if_error 1 "TF_VAR_bucket_extension not defined."
 fi
-# # init the s3 backend if it doesn't exist.
-# terraform init \
-#     -input=false \
-#     -backend-config="bucket=state.terraform.$TF_VAR_bucket_extension" \
-#     -backend-config="key=main/vpc/terraform.tfstate" \
-#     -backend-config="region=$AWS_DEFAULT_REGION" \
-#     -backend-config="dynamodb_table=locks.state.terraform.$TF_VAR_bucket_extension"
-# terraform plan -out=tfplan -input=false -var "sleep=true"
 
 cd $SCRIPTDIR/modules/vpc
 ./generate-plan
@@ -35,6 +38,10 @@ fi
 
 echo "Running Consul..."
 sudo /opt/consul/bin/run-consul --client --cluster-tag-key "${consul_cluster_tag_key}" --cluster-tag-value "${consul_cluster_tag_value}"
+
+if [[ -z "$VAULT_TOKEN" ]]; then
+    exit_if_error 1 "VAULT_TOKEN not defined.  This is required to continue deploying hosts that will require vault for certificates."
+fi
 
 cd $SCRIPTDIR/modules/terraform-aws-bastion
 ./generate-plan
