test retries

diff --git a/modules/vault/post-tf-vault-login b/modules/vault/post-tf-vault-login
--- a/modules/vault/post-tf-vault-login
+++ b/modules/vault/post-tf-vault-login
@@ -2,12 +2,47 @@
 
 set -e
 
+# Log the given message. All logs are written to stderr with a timestamp.
+function log {
+ local -r message="$1"
+ local readonly timestamp=$(date +"%Y-%m-%d %H:%M:%S")
+ >&2 echo -e "$timestamp $message"
+}
+# A retry function that attempts to run a command a number of times and returns the output
+function retry {
+  local -r cmd="$1"
+  local -r description="$2"
+
+  for i in $(seq 1 30); do
+    log "$description"
+
+    # The boolean operations with the exit status are there to temporarily circumvent the "set -e" at the
+    # beginning of this script which exits the script immediatelly for error status while not losing the exit status code
+    output=$(eval "$cmd") && exit_status=0 || exit_status=$?
+    log "$output"
+    if [[ $exit_status -eq 0 ]]; then
+      echo "$output"
+      return
+    fi
+    log "$description failed. Will sleep for 10 seconds and try again."
+    sleep 10
+  done;
+
+  log "$description failed after 30 attempts."
+  exit $exit_status
+}
+
 if [[ -z "$VAULT_TOKEN" ]]; then
     echo "Instances from this point require you to login to vault.  To avoid this message you can define the var VAULT_TOKEN"
 fi
 
 echo "Waiting for consul vault service (Ignore the following connection errors for a reasonable period until connection is established)..."
-until consul catalog services | grep -m 1 "vault"; do sleep 1 ; done
+# until consul catalog services | grep -m 1 "vault"; do sleep 1 ; done
+
+retry \
+    "consul catalog services | grep -m 1 'vault' || sleep 1"
+    "Waiting for consul vault service..."
+
 until vault status | grep -m 1 "Initialized.*"; do sleep 1 ; done
 
 initialised=true
